'use strict';

const { WebSocketServer } = require('ws');
const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

const WS_PORT  = process.env.PORT     || 8080;  // plain ws://  (Chrome / curl)
const WSS_PORT = process.env.WSS_PORT || 8443;  // wss://       (Firefox extension)

// ---------- TLS cert (generated by setup.js) ----------

const CERT_FILE = path.join(__dirname, '.cert', 'cert.pem');
const KEY_FILE  = path.join(__dirname, '.cert', 'key.pem');

function getCert() {
  return { cert: fs.readFileSync(CERT_FILE), key: fs.readFileSync(KEY_FILE) };
}

// ---------- Shared room state ----------

// rooms: Map<roomId, { clients: Client[], hostToken: string }>
// Client: { ws, id, isHost }
const rooms = new Map();
let clientCounter = 0;

// ---------- Connection handler (shared by both servers) ----------

function handleConnection(ws, req) {
  const id = `c${++clientCounter}`;
  const origin = req.headers.origin ?? '(no origin)';
  const secure = req.socket.encrypted ? 'wss' : 'ws';
  console.log(`[${id}] connected via ${secure}  origin=${origin}`);

  let roomId = null;
  let isHost = false;

  ws.on('message', (raw) => {
    let msg;
    try { msg = JSON.parse(raw); } catch {
      console.log(`[${id}] bad JSON, ignoring`);
      return;
    }

    // --- Join ---
    if (msg.type === 'join') {
      if (roomId) return;
      roomId = String(msg.room).replace(/[^a-z0-9-]/gi, '').slice(0, 32);
      if (!roomId) return;

      const hostToken = msg.hostToken ? String(msg.hostToken).slice(0, 64) : null;

      if (!rooms.has(roomId)) {
        // First joiner creates the room; their token becomes the permanent host token
        rooms.set(roomId, { clients: [], hostToken });
      }

      const room = rooms.get(roomId);
      // Host is whoever presents the matching token (survives reconnects and race conditions)
      isHost = !!hostToken && hostToken === room.hostToken;

      room.clients.push({ ws, id, isHost });

      console.log(`[${id}] joined room="${roomId}"  isHost=${isHost}  peers=${room.clients.length - 1}`);

      ws.send(JSON.stringify({ type: 'joined', isHost, id, peers: room.clients.length - 1 }));
      broadcast(roomId, { type: 'peer-joined', id }, ws);
      return;
    }

    // --- Relay ---
    if (!roomId) {
      console.log(`[${id}] msg before join, dropping:`, msg.type);
      return;
    }
    console.log(`[${id}] relay room="${roomId}" type=${msg.type}`);
    broadcast(roomId, { ...msg, from: id }, ws);
  });

  ws.on('close', (code, reason) => {
    console.log(`[${id}] disconnected  code=${code}  reason="${reason}"  room="${roomId}"`);
    if (!roomId || !rooms.has(roomId)) return;

    const room = rooms.get(roomId);
    const idx = room.clients.findIndex(c => c.ws === ws);
    if (idx === -1) return;
    room.clients.splice(idx, 1);

    broadcast(roomId, { type: 'peer-left', id, wasHost: isHost });

    if (room.clients.length === 0) {
      console.log(`room "${roomId}" empty, deleted`);
      rooms.delete(roomId);
      return;
    }

    // With token-based host identity, we only promote if there's genuinely no
    // host token set (legacy fallback) — normally the host reconnects and
    // re-claims host status via their token.
    if (isHost && !room.hostToken) {
      room.clients[0].isHost = true;
      console.log(`[${id}] was host; promoting ${room.clients[0].id}`);
      room.clients[0].ws.send(JSON.stringify({ type: 'promoted-to-host' }));
      broadcast(roomId, { type: 'new-host', id: room.clients[0].id }, room.clients[0].ws);
    }
  });

  ws.on('error', (err) => console.log(`[${id}] error:`, err.message));
}

function broadcast(roomId, msg, exclude = null) {
  const room = rooms.get(roomId);
  if (!room) return;
  const data = JSON.stringify(msg);
  for (const client of room.clients) {
    if (client.ws !== exclude && client.ws.readyState === 1 /* OPEN */) {
      client.ws.send(data);
    }
  }
}

// ---------- Plain WS server (port 8080) ----------
// In production (Fly.io etc.) TLS is terminated by the proxy — this is all you need.

const httpServer = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('VidSync signaling server\n');
});
const wsServer = new WebSocketServer({ server: httpServer });
wsServer.on('connection', handleConnection);
httpServer.listen(WS_PORT, () =>
  console.log(`WS  listening on  ws://localhost:${WS_PORT}`)
);

// ---------- Secure WSS server (port 8443, local dev only) ----------
// Only started when a self-signed cert exists (generated by setup.js).
// Not used in production — the proxy handles TLS there.

if (fs.existsSync(CERT_FILE) && fs.existsSync(KEY_FILE)) {
  const tls = getCert();
  const httpsServer = https.createServer(tls, (req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('VidSync signaling server (WSS)\n');
  });
  const wssServer = new WebSocketServer({ server: httpsServer });
  wssServer.on('connection', handleConnection);
  httpsServer.listen(WSS_PORT, () =>
    console.log(`WSS listening on  wss://localhost:${WSS_PORT}  (local Firefox dev)`)
  );
} else {
  console.log('No TLS cert found — WSS server skipped (production mode)');
}
